[tool.poetry]
name = "oid-test"
version = "0.1.0"
description = "A test project"
authors = ["truden-dev <torgeirar@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
